# Generated by Django 5.2.11 on 2026-02-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
