# Generated by Django 5.2.11 on 2026-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_storage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
