# Generated by Django 6.0.2 on 2026-02-22 19:39

from django.db import migrations, models


def null_empty_emails(apps, schema_editor):
    User = apps.get_model('documents', 'User')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_user_role_teamjoinrequest'),
    ]

    operations = [
        # Step 1: make nullable (no unique yet) so we can set NULLs
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, null=True, max_length=254, default=None),
        ),
        # Step 2: convert existing empty strings to NULL
        migrations.RunPython(null_empty_emails, migrations.RunPython.noop),
        # Step 3: add unique constraint now that there are no duplicate values
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, null=True, max_length=254, default=None, unique=True),
        ),
    ]
