# Generated by Django 6.0.2 on 2026-02-24 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_add_credit_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
