# Generated by Django 6.0.2 on 2026-03-29 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_composite_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='type',
            field=models.CharField(choices=[('analyze', 'Document Analysis'), ('folder_combine', 'Folder Combined Analysis'), ('admin_grant', 'Admin Grant'), ('request_approved', 'Request Approved'), ('refund', 'Refund'), ('stripe_purchase', 'Stripe Purchase')], max_length=20),
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['key'],
            },
        ),
    ]
