# Generated by Django 6.0.2 on 2026-02-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_add_document_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
