# Generated by Django 6.0.2 on 2026-03-29 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='feature_flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
