# Generated by Django 6.0.2 on 2026-03-29 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        # The feature_flags_allowed_users table is created idempotently by
        # run_migrations.py using GENERATED BY DEFAULT AS IDENTITY. Using
        # SeparateDatabaseAndState here skips the DDL (which would try to
        # ALTER the id column to "serial", an unsupported type in modern
        # PostgreSQL) while still updating Django's migration state.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS feature_flags_allowed_users (
                            id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            featureflag_id bigint NOT NULL REFERENCES feature_flags(id) ON DELETE CASCADE,
                            user_id        bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                            UNIQUE (featureflag_id, user_id)
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS feature_flags_allowed_users;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='featureflag',
                    name='allowed_users',
                    field=models.ManyToManyField(blank=True, related_name='feature_flags', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
