# Generated by Django 6.0.2 on 2026-02-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_add_document_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='type',
            field=models.CharField(choices=[('analyze', 'Document Analysis'), ('folder_combine', 'Folder Combined Analysis'), ('admin_grant', 'Admin Grant'), ('request_approved', 'Request Approved'), ('refund', 'Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='CombinedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_analysis', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_analyses', to='documents.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_analyses', to=settings.AUTH_USER_MODEL)),
                ('source_documents', models.ManyToManyField(related_name='combined_in', to='documents.document')),
            ],
            options={
                'db_table': 'combined_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
